version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mihri789
      - POSTGRES_USER=mihrimurgrn
      - POSTGRES_DB=petrichor
    restart: unless-stopped

  app:
    petrichor:
    image: petrichor:latest
#    network_mode: bridge
    container_name: petrichor
    expose:
     - 8080
    restart: unless-stopped
    depends_on:
    - postgres
    ports:
    - 8080:8080
    links:
    - postgres

